# Generated by Django 3.2.4 on 2021-08-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='fees',
            field=models.FloatField(db_column='fees', default=500.0),
        ),
    ]
